// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "cat1":return img`
........................................................................c.....................................................................................
.......................................................................cccc...................................................................................
ccc..................................................................ccccccc..................................................................................
cccc................................................................ccffffff..................................................................................
ccccc..............................................................ccfffcfff..................................................................................
cfffcc............................................................ccfcceccffc.................................................................................
cfffccc.........................................................ccccceeeeecff.................................................................................
cceefccc.......................................................ccccceeeeeeecf.................................................................................
beeeffccff....................................................cfccceeeeeeeeef.................................................................................
.eeeeffccff...................................................fccfeeeeeeeeeef.................................................................................
beeeeffccfff.................................................ffcfeeeeeeeeeeec.................................................................................
.ceeeefcccffff..............................................ffcceeeeeeeeeeeecc................................................................................
.cceeeffccfffffc...........................................fffceeeeeeeeeeeeeec................................................................................
.bfeeeefccfffffff.........................................cffceeeeeeeeeeeeeeef................................................................................
..feeeefcccfffffff........................................fffeeeeeeeeeeeeeeeef................................................................................
..feeeecfccffffffff......................................ffffeeeeeeeeeeeeeeecf................................................................................
..ffeeeefcccffffffffc...................................ffffceeceeeeeeeeeeeecf................................................................................
..bfeeeecfccfffffffff...................................fffccefeeeeeeeeeeeeecf................................................................................
...feeeeefccffffffffff.................................fffcfcfeeeeeeeeeeeeeecf................................................................................
...ffeeeefcccffffffffff...............................ffffcfceeeeeeceeeeeeeecf................................................................................
...ffeeeeccccfffffffffff.............................ffffcffffceefeeeeeeeeeeff................................................................................
....feeeecfccfffffffffffc...........................fffffcfffcefeeeeeeeeeeeeff................................................................................
....ffeeeffcccfffffffffff.........cccffcc..........cffffccffffceeeeeeeeeeeecff................................................................................
....cfeeecfcccffffffffffff....cccffffffffcc...cc..ffffffcffffceeeeeeeeeeeeecff................................................................................
....bfefecfcccffffffffffff...cffffffffffffff.fccccfffffccffffffffffceeeeeeecff................................................................................
.....ffefcfcccfffffffffffffffffffffffffffffffffffffffffccfffccfffceeceeeeeccff................................................................................
.....ffeccccccffffffffffffffffffffffffffffffffffffffffccfffffcceeceeeeeeeeccff................................................................................
......feeccfccffffffffffffffffffffffffffffffffffffffffccfffffffceeeeeeeeeecfff................................................................................
......ffcfffcccffffffffffffffffffffffffffffffffffffffcccfffffceeeeeeeeeeeccfff................................................................................
......cfcfffcccffffffffffffffffffffffffffffffffffffffcccffffffcceeeeeeccccffff................................................................................
.......fccfffccffffffffffffffffffffffffffffffffffffffccfffffffccffeeecccccffff................................................................................
.......ffcfffccfffffffffffffffffffffffffffffffffffffcccffffffffcccccccccffffff................................................................................
.......fffcffcffffffffffffffffffffffffffffffffffffffcccffffffffcccccccfffffffc................................................................................
.......cffffffffffffffffffffffffffffffffffffffffffffccffffffffffffccfffffffff.................................................................................
.....bffffffffffffffffffffffffffffffffffffffffffffffccfffffffffffffffffffffff.................................................................................
........ffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.................................................................................
.....cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc.................................................................................
....ffccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb.................................................................................
.......cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..................................................................................
......bfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..................................................................................
......fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc..................................................................................
......cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb..................................................................................
.....ccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...................................................................................
....c..bcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...................................................................................
......c.cfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff....................................................................................
........ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff....................................................................................
.......cfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc....................................................................................
.......ffffccccccccffffffffffffffffffffffccccccccccffffffffffffffffffffff.....................................................................................
......bfffcccccccccccffffffffffffffffffccccccccccccccfffffffffffffffffff...cc.................................................................................
......fffcccffffffccccffffffffffffffffcccccccffffccccccffffffffffffffffcc.fff.................................................................................
......ffccffffffffffcccffffffffffffffcccccfffffffffcccccfffffffffffffffffffc..................................................................................
......ffccffffffffffccccfffffffffffffccccfffffffffffccccfffffffffffffffffffc..................................................................................
.....cfccfffffffffffffccffffffffffffccccfffffffffffffccccffffffffffffffffffff...............cccc..............................................................
.....cfccfffffffffffffccffffffffffffcccfffffffffffffd1ccccfffffffffffffffffffcc...........ccfff...............................................................
.....cfccffffffffffff11cfffffffffffccccfffffffffffffffccccfffffffffffffffffffffffcc...c.cccfff................................................................
.....cfccfffffffffffffccfffffffffffcccfffffffffffffffffcccffffffffffffffffffffffff..ccfffffffccffffcc.........................................................
....ccfccfffffffffffffccfffffffffffcccfffffffffffffffffcccffffffffffffffffffffffcc.ffffffffffffffffffc........................................................
...cccfceffffffffffffeecfffffffffffcccfffffffffffffffffcccfffffffffffffffffffffffffffffffffffffffffffcc.......................................................
...ccccfeffffffffffffeecfffffffffffcccfffffffffffffffffcccfffffffffffffffffffffffffffffffffffffffccc..........................................................
..cccccfbffffffffffffeecfffffffffffcccfffffffffffffffffcccffffffffffffffffffffffffffffffffffffffc.............................................................
..cccccfeefffffffffffeecfffffffffffceefffffffffffffffffbecfffffffffffffffffffffffffffffffffffffffc............................................................
.cccccccfeffffffffffeeecfffffffffffc44ffffffffffffffffb4effffffffffffffffffffffffffffffffffffffffffc..........................................................
ccccccccfeefffffffffeecfffffffffffff44bfffffffffffffff44effffffffffffffffffffffffffffffffffffffffffc..........................................................
cccccccccfeefffffffe4effffffffffffff444efffffffffffff444fffffffffffffffffffffffffffffffffffffffffffff.........................................................
fff.cccccffeefffffe4effffffffffffffff444bfffffffffff444effffffffffffffffffffffffffffffffffffffffffffff........................................................
...cccccccffe4eeee44effffffffffffffffc4444ecffffffe444efffffffffffffffffffffffffffffffffffffffffffffc.c.......................................................
...ccccccccffeeeeeeffffffffffcccfffffff444444eee44444efffffffffffffffffffffffffffffffffffffffffffffff.........................................................
..cccccccccccffffffffffffffffccccccfffffb4444444444ecfffffffffffffffffffffffffffffffffffffffffffffffff........................................................
..cccccccccccffcccccffffffffcccccccccfffffe4444becfffffffffffffffffffffffffffffffffffffffffffffffffffff.......................................................
..ccccccccfffffcccccfffffffcccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc......................................................
...cccccffffffcccccccfffffccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc.....................................................
....ffcfffffffcccccccccffcccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc.....................................................
.......cccffffccccccccccfcccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff....................................................
...........cfffccccccccfffccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc...................................................
..............cfccccccffffffccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc...................................................
................cccccffffffffffcccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc..................................................
.......................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..................................................
.........................effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc.................................................
.............................dbccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcc................................................
..................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc................................................
..................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcc...............................................
..................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff................................................
..................................cfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc...............................................
..................................bfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcf..............................................
...................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
...................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...............................................
...................................effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb.............................................
....................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb.............................................
....................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc.............................................
....................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc............................................
....................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcf............................................
....................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcb...........................................
....................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.c...........................................
.....................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc............................................
.....................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff............................................
.....................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcc...........................................
.....................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcc...........................................
.....................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc............................................
.....................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc............................................
.....................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc............................................
.....................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc............................................
.....................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcc............................................
.....................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc.............................................
.....................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc............................................
......................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff............................................
......................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff............................................
......................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..........................................
......................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.........................................
......................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc........................................
......................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc.......................................
.......................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcc.....................................
.......................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc......................................
.......................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc......................................
.......................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccb....................................
.......................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc.....................................
.......................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff........................................
........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc........................................
........................................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff........................................
........................................cfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcf........................................
........................................fcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb.........................................
........................................ccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb.........................................
.........................................cfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb..........................................
.........................................cfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...........................................
.........................................ccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc...........................................
.........................................ccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..........bcff..............................
.........................................ccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccb..b..cffffffc...............................
.........................................cccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb.cc.ffffffff..................................
..........................................ccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..ccfffffff.....................................
..........................................ccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..fffffffffffffffffffcb..........................
..........................................ccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc......................
..........................................ccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc...................
...........................................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc.................
..........................................cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfffccc.............
...........................................cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffcc..........
...........................................cfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc........
.................................fffcccc...cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfcc..cfffffffffffffffffffffffffffc......
...............................cfffffcfff..cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcb.................bffffffffffffffffffffffc.....
..............................cffffffccfffccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc.........................cffffffffffffffffffffc....
..............................ffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb..............................cfffffffffffffffffffc...
.............................cffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc.b..................................ccffffffffffffffffb...
.............................cfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc.....................................cfffffffffffffffffbb.
.............................cffffffffffffffffffffffffffffffffffffffffffffffc..cffffffffffffffffffffffb.....................................fffffffffffffffbfc
..............................ffffffffffffffffffffffffffffffffffffffffffffffc....ffffffffffffffffffffffb.....................................ccffffffffffffffc
.............................cfffffffffffffffffffffffffffcffffffffffffffffffc......fffffffffffffffffffffb......................................ccffffffffffffc
..............................ffffffffffffffffffffffffc.ccfffffffffffffffffff.......ccffffffffffffffffffc.........................................ccfffffffffb
..............................cfffffffffffffffffffffff......ffffffffffffffffc..........ffffffffffffffffff...........................................ccccccbc..
.................................cfffffffffffffffffffc......cfffffffffffffff............ccfffffffffffffffb....................................................
..................................cffffffffffffffccc.........cfffffffffffffc..............cfffffffffffffc.....................................................
...............................................................cffffffffcc...................cffffffffffc.....................................................
..................................................................ccfccc........................ffffccfb......................................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
